package keluargawna;

import javax.ejb.*;
import java.util.*;
import java.math.*;
import java.sql.Date;

public interface BiodataWna3 extends javax.ejb.EJBLocalObject {
  public BigDecimal getNik();
  public void setNamaKlrga(String namaKlrga);
  public String getNamaKlrga();
  public void setNamaPertma(String namaPertma);
  public String getNamaPertma();
  public void setJenisKlmin(BigDecimal jenisKlmin);
  public BigDecimal getJenisKlmin();
  public void setTmptLhr(String tmptLhr);
  public String getTmptLhr();
  public void setTglLhr(Date tglLhr);
  public Date getTglLhr();
  public void setKwrngrn(String kwrngrn);
  public String getKwrngrn();
  public void setAgama(String agama);
  public String getAgama();
  public void setGolDrh(BigDecimal golDrh);
  public BigDecimal getGolDrh();
  public void setStatKwn(BigDecimal statKwn);
  public BigDecimal getStatKwn();
  public void setPddkAkh(BigDecimal pddkAkh);
  public BigDecimal getPddkAkh();
  public void setJenisPkrjn(BigDecimal jenisPkrjn);
  public BigDecimal getJenisPkrjn();
  public void setAlamatSpsor(String alamatSpsor);
  public String getAlamatSpsor();
  public void setNoRt(BigDecimal noRt);
  public BigDecimal getNoRt();
  public void setNoRw(BigDecimal noRw);
  public BigDecimal getNoRw();
  public void setKodepos(BigDecimal kodepos);
  public BigDecimal getKodepos();
  public void setTelepon(String telepon);
  public String getTelepon();
  public void setDatngDari(String datngDari);
  public String getDatngDari();
  public void setTujuanDtng(String tujuanDtng);
  public String getTujuanDtng();
  public void setNoPaspor(String noPaspor);
  public String getNoPaspor();
  public void setTglPaspor(Date tglPaspor);
  public Date getTglPaspor();
  public void setTglAkhPaspor(Date tglAkhPaspor);
  public Date getTglAkhPaspor();
  public void setNamaSpsor(String namaSpsor);
  public String getNamaSpsor();
  public void setTipeSpsor(BigDecimal tipeSpsor);
  public BigDecimal getTipeSpsor();
  public void setDokImgr(BigDecimal dokImgr);
  public BigDecimal getDokImgr();
  public void setNoDok(String noDok);
  public String getNoDok();
  public void setTmptDtbit(String tmptDtbit);
  public String getTmptDtbit();
  public void setTglDtbit(Date tglDtbit);
  public Date getTglDtbit();
  public void setTglAkhDok(Date tglAkhDok);
  public Date getTglAkhDok();
  public void setTmptDtngPert(String tmptDtngPert);
  public String getTmptDtngPert();
  public void setTglDtngPert(Date tglDtngPert);
  public Date getTglDtngPert();
  public void setNoStld(String noStld);
  public String getNoStld();
  public void setTglDft(Date tglDft);
  public Date getTglDft();
  public void setNamaDin(String namaDin);
  public String getNamaDin();
  public void setNamaKepDin(String namaKepDin);
  public String getNamaKepDin();
  public void setNipKepDin(BigDecimal nipKepDin);
  public BigDecimal getNipKepDin();
  public void setNamaPetEntri(String namaPetEntri);
  public String getNamaPetEntri();
  public void setNipPetEntri(BigDecimal nipPetEntri);
  public BigDecimal getNipPetEntri();
  public void setTglEntri(Date tglEntri);
  public Date getTglEntri();
  public void setNoKk(BigDecimal noKk);
  public BigDecimal getNoKk();
  public void setNoProp(BigDecimal noProp);
  public BigDecimal getNoProp();
  public void setNoKab(BigDecimal noKab);
  public BigDecimal getNoKab();
  public void setStatKtp(BigDecimal statKtp);
  public BigDecimal getStatKtp();
  public void setStatHidup(BigDecimal statHidup);
  public BigDecimal getStatHidup();
  public void setTglUbah(Date tglUbah);
  public Date getTglUbah();
  public void setNoKec(BigDecimal noKec);
  public BigDecimal getNoKec();
  public void setNoKel(BigDecimal noKel);
  public BigDecimal getNoKel();
  public void setStatHbkel(BigDecimal statHbkel);
  public BigDecimal getStatHbkel();
  public void setTglCetakKtp(Date tglCetakKtp);
  public Date getTglCetakKtp();
  public void setTglGantiKtp(Date tglGantiKtp);
  public Date getTglGantiKtp();
  public void setTglPjgKtp(Date tglPjgKtp);
  public Date getTglPjgKtp();
  public void setAlsNumpang(BigDecimal alsNumpang);
  public BigDecimal getAlsNumpang();
  public void setPflag(String pflag);
  public String getPflag();
  public void setCflag(String cflag);
  public String getCflag();
}