package keluargawna;

import javax.ejb.*;
import java.util.*;
import java.math.*;
import java.sql.Date;

public interface PindahWniWna1 extends javax.ejb.EJBLocalObject {
  public BigDecimal getNoKk();
  public void setAlsPndh(BigDecimal alsPndh);
  public BigDecimal getAlsPndh();
  public void setAlamatTjpndh(String alamatTjpndh);
  public String getAlamatTjpndh();
  public void setNoRtTjpndh(String noRtTjpndh);
  public String getNoRtTjpndh();
  public void setNoRwTjpndh(String noRwTjpndh);
  public String getNoRwTjpndh();
  public void setKodeposTjpndh(BigDecimal kodeposTjpndh);
  public BigDecimal getKodeposTjpndh();
  public void setTelpTjpndh(String telpTjpndh);
  public String getTelpTjpndh();
  public void setNoProp(BigDecimal noProp);
  public BigDecimal getNoProp();
  public void setNoKab(BigDecimal noKab);
  public BigDecimal getNoKab();
  public void setNoKec(BigDecimal noKec);
  public BigDecimal getNoKec();
  public void setNoKel(BigDecimal noKel);
  public BigDecimal getNoKel();
  public void setJenisKpndhn(BigDecimal jenisKpndhn);
  public BigDecimal getJenisKpndhn();
  public void setRencTgl(String rencTgl);
  public String getRencTgl();
  public void setKlasfPndh(BigDecimal klasfPndh);
  public BigDecimal getKlasfPndh();
  public void setNamaKep(String namaKep);
  public String getNamaKep();
  public void setNamaCmat(String namaCmat);
  public String getNamaCmat();
  public void setNamaBup(String namaBup);
  public String getNamaBup();
  public void setNamaPetEntri(String namaPetEntri);
  public String getNamaPetEntri();
  public void setNipPetEntri(BigDecimal nipPetEntri);
  public BigDecimal getNipPetEntri();
  public void setTglEntri(String tglEntri);
  public String getTglEntri();
  public void setDusun(String dusun);
  public String getDusun();
  public void setNik(BigDecimal nik);
  public BigDecimal getNik();
  public void setNamaKk(String namaKk);
  public String getNamaKk();
  public void setNamaProp(String namaProp);
  public String getNamaProp();
  public void setNamaKab(String namaKab);
  public String getNamaKab();
  public void setNamaKec(String namaKec);
  public String getNamaKec();
  public void setNamaKel(String namaKel);
  public String getNamaKel();
  public void setNopropasl(String nopropasl);
  public String getNopropasl();
  public void setNokabasl(String nokabasl);
  public String getNokabasl();
  public void setNokecasl(String nokecasl);
  public String getNokecasl();
  public void setNokelasl(String nokelasl);
  public String getNokelasl();
}