package com.P4B;

import javax.ejb.*;
import java.util.*;
import java.math.*;
import java.sql.Date;

public interface BiodataWni1 extends javax.ejb.EJBLocalObject {
  public String getNik();
  public void setNoKtp(String noKtp);
  public String getNoKtp();
  public void setTmptSbl(String tmptSbl);
  public String getTmptSbl();
  public void setNoPaspor(String noPaspor);
  public String getNoPaspor();
  public void setTglAkhPaspor(String tglAkhPaspor);
  public String getTglAkhPaspor();
  public void setNamaLgkp(String namaLgkp);
  public String getNamaLgkp();
  public void setJenisKlmin(String jenisKlmin);
  public String getJenisKlmin();
  public void setTmptLhr(String tmptLhr);
  public String getTmptLhr();
  public void setTglLhr(String tglLhr);
  public String getTglLhr();
  public void setAktaLhr(String aktaLhr);
  public String getAktaLhr();
  public void setNoAktaLhr(String noAktaLhr);
  public String getNoAktaLhr();
  public void setGolDrh(String golDrh);
  public String getGolDrh();
  public void setAgama(String agama);
  public String getAgama();
  public void setStatKwn(String statKwn);
  public String getStatKwn();
  public void setAktaKwn(String aktaKwn);
  public String getAktaKwn();
  public void setNoAktaKwn(String noAktaKwn);
  public String getNoAktaKwn();
  public void setTglKwn(String tglKwn);
  public String getTglKwn();
  public void setAktaCrai(String aktaCrai);
  public String getAktaCrai();
  public void setNoAktaCrai(String noAktaCrai);
  public String getNoAktaCrai();
  public void setTglCrai(String tglCrai);
  public String getTglCrai();
  public void setStatHbkel(String statHbkel);
  public String getStatHbkel();
  public void setKlainFsk(String klainFsk);
  public String getKlainFsk();
  public void setPnydngCct(String pnydngCct);
  public String getPnydngCct();
  public void setPddkAkh(String pddkAkh);
  public String getPddkAkh();
  public void setJenisPkrjn(String jenisPkrjn);
  public String getJenisPkrjn();
  public void setNikIbu(String nikIbu);
  public String getNikIbu();
  public void setNamaLgkpIbu(String namaLgkpIbu);
  public String getNamaLgkpIbu();
  public void setNikAyah(String nikAyah);
  public String getNikAyah();
  public void setNamaLgkpAyah(String namaLgkpAyah);
  public String getNamaLgkpAyah();
  public void setNamaKetRt(String namaKetRt);
  public String getNamaKetRt();
  public void setNamaKetRw(String namaKetRw);
  public String getNamaKetRw();
  public void setNamaPetReg(String namaPetReg);
  public String getNamaPetReg();
  public void setNipPetReg(String nipPetReg);
  public String getNipPetReg();
  public void setNamaPetEntri(String namaPetEntri);
  public String getNamaPetEntri();
  public void setNipPetEntri(String nipPetEntri);
  public String getNipPetEntri();
  public void setTglEntri(String tglEntri);
  public String getTglEntri();
  public void setNoKk(String noKk);
  public String getNoKk();
  public void setJenisBntu(String jenisBntu);
  public String getJenisBntu();
  public void setNoProp(String noProp);
  public String getNoProp();
  public void setNoKab(String noKab);
  public String getNoKab();
  public void setNoKec(String noKec);
  public String getNoKec();
  public void setNoKel(String noKel);
  public String getNoKel();
  public void setStatHidup(String statHidup);
  public String getStatHidup();
  public void setTglUbah(String tglUbah);
  public String getTglUbah();
  public void setTglCetakKtp(String tglCetakKtp);
  public String getTglCetakKtp();
  public void setTglGantiKtp(String tglGantiKtp);
  public String getTglGantiKtp();
  public void setTglPjgKtp(String tglPjgKtp);
  public String getTglPjgKtp();
  public void setStatKtp(String statKtp);
  public String getStatKtp();
  public void setAlsNumpang(String alsNumpang);
  public String getAlsNumpang();
  public void setPflag(String pflag);
  public String getPflag();
  public void setCflag(String cflag);
  public String getCflag();
}